###############################################################
# Program:
#     Assignment 05, Order Tracking
#     Brother Comeau, CS165
# Author:
#     Leonardo Santos
# Summary:
#    This project will build up using the last project
#    (assign04) and will create classes to manage orders and 
#    customers as well.   
###############################################################


# We will learn fancier compilation steps later, but this is
# good enough for now...
a.out : product.h product.cpp address.h address.cpp customer.h customer.cpp order.h order.cpp assign05.cpp
	g++ product.cpp address.cpp customer.cpp order.cpp assign05.cpp

